### ISSUE TITLE
nk3: wrong serial, firmware and info reported

### ISSUE THREAD

**Issue by primalmotion** [Nitrokey/nitrokey-hotp-verification#23]
Hello, I'm working on adding support for the nk3 and Pureboot. I got mostly everything working, but it seems the latest master of this app behave badly regarding getting info about the card.

When I run hotp_verification info with a LibremKey (so a nk2, IIRC) I get 

```
Connected device status:
 	Card serial: 0xA585
	Firmware: v0.10
	Card counters: Admin 3, User 3
Operation success
```

But with the nk3 inserted, I get 

```
Connected device status:
 	Card serial: 0x0
	Firmware: v0.0
	Card counters: Admin 255, User 255
Operation success
```

**Comment by szszszsz** [comment]
Hey! I will take a look into it

**Comment by szszszsz** [comment]
This shows up, when the PIN attempt counter is not initialized - set the PIN to get the PIN attempt counter.
Because of that the processing is aborted, and the firmware version is not parsed from the received data, resulting in placeholder values shown to user.

To do:
- [ ] Add missing proper message about that case
- [ ] Always provide firmware version

The card serial getting is not handled for Nitrokey 3 by design for this release. Would you find it handy?

**Comment by primalmotion** [comment]
I don't need anything on that front, since everything works regarding Pureboot. I just wanted to report these small hiccups :)

**Comment by szszszsz** [comment]
Should be corrected in v1.4-RC3. Please reopen otherwise.
Serial number will be returned since the Secrets App v0.11 (not released). `0x0` will be shown until then, or if the user will decide to hide it.

**Comment by primalmotion** [comment]
I don't undertsand the message `Card counters: PIN is not set - set PIN before the first use`
I do have a PIN set.  Does that message mean to unlock the card, before using hotp_verification?

**Comment by szszszsz** [comment]
Hey, sorry for the delay.
I presume you have it set for the OpenPGP card. Currently the PIN needs to be set per application. It can be set with `pynitrokey nk3 secrets set-pin`, but it is not required for the use in Heads.

**Comment by primalmotion** [comment]
that works. thanks!
