### ISSUE TITLE
V1.5 : NK3 currently accepts any PIN on HOTP secret sealing

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-hotp-verification#30]
Edit: Renamed title after https://github.com/Nitrokey/nitrokey-hotp-verification/issues/30#issuecomment-2073971184 this is not just counter problems, nk3 requires another PIN (unknown until now) to be set which is not set and accepts anything provided. This VOIDS trustworthy remote attestation against nk3 altogether. 

Explanations on nk3 implementation  vs previous nitrokeys and librem key(nk2 pro) implementations at https://github.com/Nitrokey/nitrokey-hotp-verification/issues/30#issuecomment-2072120751

---

On boot:
![image.jpg](https://github.com/Nitrokey/nitrokey-hotp-verification/assets/827570/177537fb-de74-4beb-82f8-7b10d007b9fb)

On HOTP sealing:
![PXL_20240422_205259223.MP.jpg](https://github.com/Nitrokey/nitrokey-hotp-verification/assets/827570/154ec628-d60b-490a-b680-9d5bd09c02da)

Those counters are used under Heads logic to facilite OEM->User first time use until re-ownership is run to control the security components of the computer. If signature age is young and PIN counter was 3, as it should be reported, both user experience and OEM experience would be facilitated.

But bugs prevent Heads code to do the right thing.

**Comment by tlaurion** [comment]
Nevermind, #31 didn't fix it and I won't fix that tonight.

**Comment by tlaurion** [comment]
Why https://github.com/Nitrokey/nitrokey-hotp-verification/blob/master/src%2Freturn_codes.c#L38?

**Comment by daringer** [comment]
The firmware version is also obviously incorrect, I suppose some meta-data-struct is not parsed correctly

**Comment by tlaurion** [comment]
> The firmware version is also obviously incorrect, I suppose some meta-data-struct is not parsed correctly

Opened #33 to track this

**Comment by tlaurion** [comment]
This issue is fixed under https://github.com/Nitrokey/nitrokey-hotp-verification/pull/32 and https://github.com/linuxboot/heads/pull/1640

**Comment by tlaurion** [comment]
@daringer @jans23 @szszszsz impacts of this bug detailed at https://github.com/linuxboot/heads/issues/1645#issuecomment-2070909995 since hotp_verification output used to take various decisions under Heads.

**Comment by daringer** [comment]
ahhh, ok this makes perfect sense reading: https://github.com/Nitrokey/nitrokey-hotp-verification/issues/30#issuecomment-2060698008

although this bug is essentially a "feature" that we report the "secrets-app"-version, the overall expectation is to behave similar to what the nitrokey pro2 does, which is clearly in a wider scope as only the secrets-app...

So from what I see the behavior should be the following:
* Firmware version returns the _firmware_ version, not the secrets-app version. From my pov this could stay like that, the version is not really used inside HEADS
* the more important part is `Card counters` (see first screenshot in the top post), which should report the remaining "user pin" retries from the OpenPGPCard App, this is used in HEADS 

@tlaurion can you confirm, that this is what we would need ?

**Comment by JonathonHall-Purism** [comment]
@daringer Could you clarify the behavior of the independent HOTP PIN please?  (I don't have any of the newer tokens)

* If it's not set, does this mean a reverse HOTP initialize works with any PIN / the PIN is ignored?
* Once it's set, are there a limited number of attempts allowed (like the PGP card admin PIN) or are the attempts unlimited?
* Is there a way Heads could set the reverse HOTP PIN?
* Is there a way Heads can tell whether the token's HOTP and PGP card admin PINs are shared or independent?

I tend to think that we should not try to hide this behavior from Heads, it seems like that would create a long drawn out problem of Heads not being able to correctly say which PIN it is asking for, not being able to reset PINs correctly, etc.  I think Heads is pretty close to handling this behavior correctly too.

It looks like seal-hotpkey is mostly correct, it already says it is asking for the HOTP key admin PIN (not PGP card PIN).  It already looks for the card counters and could detect "PIN is not set" without too much trouble, perhaps not ask for a PIN at all in that case rather than asking for one that doesn't exist yet.

OEM reset probably should consider this an additional PIN/password component if the HOTP pin is separate.  It already negotiates several other components, so I think we could integrate this too.

**Comment by tlaurion** [comment]
> Essentially we should do one of the following to resolve that:\n\n\"fake\" a admin pin counter, and always output some number >= 3 (minimal invasive, I would suggest this)\nchange the hotp-verification behavior to also set the pin on the secrets app during initialization (this would most likely break backwards compatibility with already enrolled nitrokey 3 devices and on top might confuse users, which are using the secrets-app for more than only HEADS-based hotp)\n@tlaurion do you have a preferred (or different) way to resolve that ?


None of those solutions are "secure" @daringer and are a regression as opposed to nk1/nk2 I'm afraid.

What I'm reading is that anyone having access to a nks3 and laptop unattended can actually seal reverse HOTP without validating the admin PIN. Am I getting this right?

**Comment by tlaurion** [comment]
I just tested....

I entered 123456789 as Admin PIN (where it's supposed to be 12345678) and it succeeded.

This is a disaster.

**Comment by tlaurion** [comment]
Othersie I totally agree with @JonathonHall-Purism implementations sugestions.

**Comment by daringer** [comment]
> * If it's not set, does this mean a reverse HOTP initialize works with any PIN / the PIN is ignored?
> * Once it's set, are there a limited number of attempts allowed (like the PGP card admin PIN) or are the attempts unlimited?
> * Is there a way Heads could set the reverse HOTP PIN?
> * Is there a way Heads can tell whether the token's HOTP and PGP card admin PINs are shared or independent?

* yes
* limited, the secrets app has 8 tries
* not currently, `hotp-verification` needs changes for that
* no, there are always shared

no discussion, that's a regression - we are already planning the changes and the respective changes. 

> None of those solutions are "secure"

we plan to have the same behavior, which would be option 2, this would make it behave like the pro? 
In a 2nd step we could then add this pin explicitly to HEADS to be more transparent for the user, if the user requests that?

**Comment by JonathonHall-Purism** [comment]
> > It looks like seal-hotpkey is mostly correct, it already says it is asking for the HOTP key admin PIN (not PGP card PIN).
> 
> No. It asks for the (GPG) Admin PIN.

Yeah you're right.  It's different from what GPG says for the admin pin, and it made sense to me as "different" when thinking about this issue, but it's not really that different.

**Comment by JonathonHall-Purism** [comment]
> * no, they are always separated

Well I meant "for any token" know whether they are the same or separate.  So I guess at this moment we'd have to hard-code a list of tokens.  But I suppose it's a moot point if we're moving back to unifying them again.



> we plan to have the same behavior, which would be option 2, this would make it behave like the pro?
> In a 2nd step we could then add this pin explicitly to HEADS to be more transparent for the user, if the user requests that?

By option 2, do you mean:

> * change the hotp-verification behavior to also set the pin on the secrets app during initialization (this would most likely break backwards compatibility with already enrolled nitrokey 3 devices and on top might confuse users, which are using the secrets-app for more than only HEADS-based hotp)

My gut reaction is that while this is better than the current Heads behavior with these tokens, it seems like an uncomfortable middle ground overall.  The two pins are both reset during OEM reset, but if you change one it won't change the other.  (If I understand the idea correctly, anyway.)  I'm thinking about how I'd explain this to a user and it seems challenging to keep track of.

What is the use case for a user wanting these two PINs to be separate, at least separate such that changing one doesn't change the other?

Re: breaking compatibility with already-enrolled NK3 devices - I think breaking compatibility to the extent that an HOTP re-seal is needed is OK.  Updating Heads requires an HOTP re-seal anyway.  It should not require any further manual steps though.  (But we could add additional logic to Heads during HOTP reseal if needed as long as it's automatic, IMO.)

**Comment by tlaurion** [comment]
I saw https://github.com/Nitrokey/trussed-secrets-app/pull/114

Where can I see progress on hotp-verification code and Heads code to fix the issue?

**Comment by tlaurion** [comment]
Fixed with work related around https://github.com/linuxboot/heads/pull/1684#issuecomment-2133784078

**Comment by tlaurion** [comment]
This resulted in https://www.nitrokey.com/blog/2024/heads-v25-and-nitrokey-3-firmware-v171-security-update
- new firmware for nk3: 1.7.1
- new hotp-verification: 1.6

From blogpost (No CVE):
> With previous firmware versions, re-creating HOTP secrets only required User Presence, but did not verify the user PIN, which was a less strict security policy than intended.
